baseURL = 'https://example.org/'
languageCode = 'en-us'
theme = "blowfish"

[params.home]
    enable = true
    name = "Welcome!"

    [params.home.posts]
        enable = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
