baseURL = "https://radioreboot.gr/"
languageCode = 'el-gr'
title = 'Radio Reboot'
theme = "blowfish"

[params.home]
    enable = true
    name = "Welcome!"

    [params.home.posts]
        enable = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true 