baseURL = "https://bmourtzis.github.io/rebooting-reboot/"
languageCode = 'el-gr'
title = 'Radio Reboot'
theme = "blowfish"

[params]
    favicon = "favicon.png"
    colorMode = "light"
    colorModeToggle = false
[params.home]
    enable = true
    name = "Welcome!"

    [params.home.posts]
        enable = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true